apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: epitrello
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: epitrello
data:
  NODE_ENV: 'production'
  PORT: '5000'
  MONGODB_URI: 'mongodb://mongodb:27017/epitrello'
  # CLIENT_URL sera override par l'ingress en production
  CLIENT_URL: 'https://epitrello.example.com'
